### ISSUE TITLE
Code implement question

### ISSUE THREAD

**Issue by Noobzm** [stat-ml/face-evaluation#38]
```
                output = self.backbone(img)
                output.update(self.scale_predictor(**output))

                features = F.normalize(output["feature"], dim=1)
                scale = output["scale"]
```
Is the MLP connected to the last layer or the penultimate layer of the backbone network?

**Comment by mephody-bro** [comment]
Yeah, penultimate
I think it's a little bit cleaner / clear in cross-pose experiment, see https://github.com/stat-ml/face-evaluation/blob/e0af95bb016a5442daa7786ba1e4afc067819c47/face_lib/evaluation/cross.py#L109
